title: OS2forms Documentation
description: Documentation for using, hosting and developing the OS2forms project
theme: just-the-docs

logo: "/assets/site/OS2forms.svg"
favicon_ico: "/assets/site/favicon.ico"

aux_links:
  github.com/os2forms: https://github.com/os2forms
  os2.eu/os2forms: https://www.os2.eu/os2forms

just_the_docs:
  aux_scripts:
    - 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js'
    - '/assets/js/mermaid-init.js'
