title: OS2forms Documentation
description: Documentation site for OS2forms
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  github.com/os2forms: https://github.com/os2forms
  os2.eu/os2forms: https://www.os2.eu/os2display
